---
- name: "disable USBAUTO for gpsd"
  become: yes
  become_user: root
  ansible.builtin.ini_file:
    path: "/etc/default/gpsd"
    option: "USBAUTO"
    value: '"false"'
    no_extra_spaces: yes
    backup: false
  notify:
    - restart gpsd
- name: "set devices for gpsd"
  become: yes
  become_user: root
  ansible.builtin.ini_file:
    path: "/etc/default/gpsd"
    option: "DEVICES"
    value: '"/dev/serial0 /dev/pps0"'
    no_extra_spaces: yes
    backup: false
  notify:
    - restart gpsd
- name: "set options for gpsd"
  become: yes
  become_user: root
  ansible.builtin.ini_file:
    path: "/etc/default/gpsd"
    option: "GPSD_OPTIONS"
    value: '"-n"'
    no_extra_spaces: yes
    backup: false
  notify:
    - restart gpsd
- name: "ensure gpsd is running"
  become: yes
  become_user: root
  ansible.builtin.systemd_service:
    name: "gpsd.service"
    state: started
    enabled: true
    masked: no
- name: "stop gpsd.socket"
  become: yes
  become_user: root
  ansible.builtin.systemd_service:
    name: "gpsd.socket"
    state: stopped
    enabled: false
    masked: yes

