---
- name: "systemd daemon-reload"
  become: yes
  become_user: root
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "restart gpsd.service"
  become: yes
  become_user: root
  ansible.builtin.systemd_service:
    name: "gpsd.service"
    state: restarted

